name: CI pour l'image Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le référentiel
      uses: actions/checkout@v2

    - name: Configurer Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Se connecter au registre de conteneurs GitHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Construire et pousser l'image Docker
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/docker-image-repo:latest
